In [10]:
import datetime as dt

from deq.deq import ext, live_deq, deq_col_specs, deq_bias_set_context
from spells import summon

import polars as pl
import numpy as np
pl.Config.set_tbl_rows(1000)

polars.config.Config

In [6]:
ext = {
    **ext,
    **deq_col_specs(pick_equity_mid=0.015, pick_equity_mid_index=3),
}

In [7]:
metric_filter = {'lhs': 'format_day', 'op': '<=', 'rhs': 14}
context = deq_bias_set_context(
    'OTJ', 
    metric_filter,
    observed_days=14
)
df = summon('OTJ', ['deq', 'ata', 'num_gp', 'gp_wr', 'gp_wr_b', 'gp_wr_mean', 'pct_gp', 'pick_equity', 'deq_base',
                   'gp_wr_bias', 'deq_bias_adj', 'deq_meta_adj', 'meta_regression_factor'], 
            group_by=['name', 'expansion'], filter_spec = metric_filter, extensions=ext, set_context=context).with_columns(
    pl.col('gp_wr_b').alias('mwr') - pl.col('gp_wr_mean'))
df.filter(~pl.col('deq').is_null()).sort('deq', descending=True)

shape: (364, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ name      ┆ expansion ┆ deq       ┆ ata       ┆ … ┆ deq_bias_ ┆ deq_meta_ ┆ meta_regr ┆ mwr      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ adj       ┆ adj       ┆ ession_fa ┆ ---      │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ctor      ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ ---       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Vaultborn ┆ OTJ       ┆ 0.063671  ┆ 1.418284  ┆ … ┆ -0.001251 ┆ -0.002402 ┆ -0.216462 ┆ 0.045982 │
│ Tyrant    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Railway   ┆ OTJ       ┆ 0.062704  ┆ 1.239122  ┆ … ┆ -0.000609 ┆ -0.002129 ┆ -0.216462 ┆ 0.042126 │
│ Brawler   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Bristly   ┆ OTJ       ┆ 0.060307  ┆ 1.305813  ┆ … ┆ -0.000951 ┆ -0.00256  ┆ -0.216462 ┆ 0.042249 │
│ Bill,     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Spine     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Sower     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Bristlebu ┆ OTJ       ┆ 0.057894  ┆ 1.49264   ┆ … ┆ -0.001629 ┆ -0.002611 ┆ -0.216462 ┆ 0.040906 │
│ d Farmer  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Ornery    ┆ OTJ       ┆ 0.054566  ┆ 1.437478  ┆ … ┆ -0.001375 ┆ -0.002512 ┆ -0.216462 ┆ 0.036393 │
│ Tumblewag ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ g         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Bonny     ┆ OTJ       ┆ 0.054195  ┆ 1.67931   ┆ … ┆ 0.001224  ┆ 0.001361  ┆ -0.216462 ┆ 0.033334 │
│ Pall, Cle ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ arcutter  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Collector ┆ OTJ       ┆ 0.050426  ┆ 1.805369  ┆ … ┆ -0.001636 ┆ -0.001489 ┆ -0.216462 ┆ 0.035822 │
│ 's Cage   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Hostile   ┆ OTJ       ┆ 0.050055  ┆ 1.706575  ┆ … ┆ 0.000118  ┆ 0.000125  ┆ -0.216462 ┆ 0.030542 │
│ Investiga ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ tor       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Roxanne,  ┆ OTJ       ┆ 0.049215  ┆ 1.678062  ┆ … ┆ -0.000527 ┆ -0.000588 ┆ -0.216462 ┆ 0.031325 │
│ Starfall  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Savant    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Sandstorm ┆ OTJ       ┆ 0.049106  ┆ 1.56557   ┆ … ┆ -0.001658 ┆ -0.002276 ┆ -0.216462 ┆ 0.032452 │
│ Salvager  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Overwhelm ┆ OTJ       ┆ 0.04889   ┆ 2.472365  ┆ … ┆ 0.000059  ┆ 0.000025  ┆ -0.216462 ┆ 0.036646 │
│ ing       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Forces    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Seraphic  ┆ OTJ       ┆ 0.047508  ┆ 2.134946  ┆ … ┆ -0.005893 ┆ -0.003498 ┆ -0.216462 ┆ 0.042432 │
│ Steed     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Oko,      ┆ OTJ       ┆ 0.047084  ┆ 1.296599  ┆ … ┆ 0.000219  ┆ 0.000609  ┆ -0.216462 ┆ 0.023378 │
│ Thief of  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Crowns    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Dust      ┆ OTJ       ┆ 0.046613  ┆ 1.487572  ┆ … ┆ -0.000788 ┆ -0.001278 ┆ -0.216462 ┆ 0.027064 │
│ Animus    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Colossal  ┆ OTJ       ┆ 0.045769  ┆ 1.509376  ┆ … ┆ -0.001614 ┆ -0.002492 ┆ -0.216462 ┆ 0.028163 │
│ Rattlewur ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ m         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Outcaster ┆ OTJ       ┆ 0.04418   ┆ 2.988553  ┆ … ┆ -0.004956 ┆ -0.0013   ┆ -0.216462 ┆ 0.039211 │
│ Greenblad ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ e         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Rakdos,   ┆ OTJ       ┆ 0.043266  ┆ 1.581462  ┆ … ┆ 0.001418  ┆ 0.001886  ┆ -0.216462 ┆ 0.020675 │
│ the       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Muscle    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Fractured ┆ OTJ       ┆ 0.042894  ┆ 2.230455  ┆ … ┆ 0.003164  ┆ 0.001688  ┆ -0.216462 ┆ 0.022915 │
│ Identity  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Goldvein  ┆ OTJ       ┆ 0.040284  ┆ 1.325881  ┆ … ┆ -0.000717 ┆ -0.001805 ┆ -0.216462 ┆ 0.019806 │
│ Hydra     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lassoed   ┆ OTJ       ┆ 0.040023  ┆ 3.012622  ┆ … ┆ -0.004738 ┆ -0.001225 ┆ -0.216462 ┆ 0.034228 │
│ by the    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Law       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Gisa, the ┆ OTJ       ┆ 0.03923   ┆ 1.274599  ┆ … ┆ 0.000251  ┆ 0.000757  ┆ -0.216462 ┆ 0.01527  │
│ Hellraise ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ r         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Spinewood ┆ OTJ       ┆ 0.039151  ┆ 2.856182  ┆ … ┆ -0.00558  ┆ -0.001638 ┆ -0.216462 ┆ 0.03261  │
│ s         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Armadillo ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Selvala,  ┆ OTJ       ┆ 0.037063  ┆ 1.492884  ┆ … ┆ -0.001938 ┆ -0.003105 ┆ -0.216462 ┆ 0.021179 │
│ Eager Tra ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ilblazer  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Outcaster ┆ OTJ       ┆ 0.037016  ┆ 1.681697  ┆ … ┆ -0.002187 ┆ -0.002423 ┆ -0.216462 ┆ 0.021185 │
│ Trailblaz ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ er        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Final     ┆ OTJ       ┆ 0.036905  ┆ 1.674554  ┆ … ┆ -0.001251 ┆ -0.001403 ┆ -0.216462 ┆ 0.022604 │
│ Showdown  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ The       ┆ OTJ       ┆ 0.035298  ┆ 1.541603  ┆ … ┆ -0.0012   ┆ -0.001729 ┆ -0.216462 ┆ 0.017602 │
│ Gitrog,   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Ravenous  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Ride      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Hellspur  ┆ OTJ       ┆ 0.034975  ┆ 1.842692  ┆ … ┆ 0.00275   ┆ 0.00237   ┆ -0.216462 ┆ 0.012261 │
│ Posse     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Boss      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Harvester ┆ OTJ       ┆ 0.0336    ┆ 1.681081  ┆ … ┆ 0.00028   ┆ 0.000311  ┆ -0.216462 ┆ 0.013257 │
│ of Misery ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Pest Infe ┆ OTJ       ┆ 0.033509  ┆ 2.693568  ┆ … ┆ -0.003742 ┆ -0.001268 ┆ -0.216462 ┆ 0.024968 │
│ station   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Bruse     ┆ OTJ       ┆ 0.032953  ┆ 2.166574  ┆ … ┆ -0.000065 ┆ -0.000037 ┆ -0.216462 ┆ 0.017524 │
│ Tarl,     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Roving    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Rancher   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Stingerba ┆ OTJ       ┆ 0.031394  ┆ 1.629453  ┆ … ┆ 0.001808  ┆ 0.002196  ┆ -0.216462 ┆ 0.006607 │
│ ck Terror ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Hollow    ┆ OTJ       ┆ 0.031262  ┆ 4.040831  ┆ … ┆ -0.000538 ┆ -0.000094 ┆ -0.216462 ┆ 0.023257 │
│ Marauder  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Shepherd  ┆ OTJ       ┆ 0.031021  ┆ 3.24036   ┆ … ┆ -0.006395 ┆ -0.001511 ┆ -0.216462 ┆ 0.027155 │
│ of the    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Clouds    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Beastbond ┆ OTJ       ┆ 0.0299    ┆ 3.698569  ┆ … ┆ -0.007719 ┆ -0.001532 ┆ -0.216462 ┆ 0.028237 │
│ Outcaster ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Primal    ┆ OTJ       ┆ 0.02971   ┆ 2.449342  ┆ … ┆ -0.004673 ┆ -0.00199  ┆ -0.216462 ┆ 0.020487 │
│ Might     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Throw     ┆ OTJ       ┆ 0.02928   ┆ 4.502092  ┆ … ┆ -0.009613 ┆ -0.001426 ┆ -0.216462 ┆ 0.031316 │
│ from the  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Saddle    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Nexus of  ┆ OTJ       ┆ 0.029258  ┆ 2.134313  ┆ … ┆ 0.000069  ┆ 0.000041  ┆ -0.216462 ┆ 0.011341 │
│ Becoming  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Wylie     ┆ OTJ       ┆ 0.028982  ┆ 2.524665  ┆ … ┆ -0.00873  ┆ -0.003458 ┆ -0.216462 ┆ 0.028555 │
│ Duke,     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Atiin     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Hero      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Buried in ┆ OTJ       ┆ 0.028895  ┆ 3.672177  ┆ … ┆ -0.008928 ┆ -0.00179  ┆ -0.216462 ┆ 0.030222 │
│ the       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Garden    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Fortune,  ┆ OTJ       ┆ 0.028876  ┆ 2.117411  ┆ … ┆ -0.003465 ┆ -0.002099 ┆ -0.216462 ┆ 0.017061 │
│ Loyal     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Steed     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Vadmir,   ┆ OTJ       ┆ 0.028566  ┆ 1.849685  ┆ … ┆ 0.000933  ┆ 0.000796  ┆ -0.216462 ┆ 0.007106 │
│ New Blood ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Annie     ┆ OTJ       ┆ 0.027968  ┆ 2.192308  ┆ … ┆ -0.002705 ┆ -0.001505 ┆ -0.216462 ┆ 0.017092 │
│ Flash,    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ the       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Veteran   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Stoic     ┆ OTJ       ┆ 0.027857  ┆ 1.962182  ┆ … ┆ 0.005381  ┆ 0.003941  ┆ -0.216462 ┆ 0.000631 │
│ Sphinx    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Oltec Mat ┆ OTJ       ┆ 0.027595  ┆ 1.792734  ┆ … ┆ -0.001641 ┆ -0.001522 ┆ -0.216462 ┆ 0.011283 │
│ terweaver ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Terror of ┆ OTJ       ┆ 0.027531  ┆ 1.220582  ┆ … ┆ 0.00051   ┆ 0.001942  ┆ -0.216462 ┆ 0.001358 │
│ the Peaks ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Stubborn  ┆ OTJ       ┆ 0.027137  ┆ 3.954394  ┆ … ┆ -0.00933  ┆ -0.001686 ┆ -0.216462 ┆ 0.027995 │
│ Burrowfie ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ nd        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Aloe      ┆ OTJ       ┆ 0.027007  ┆ 3.592113  ┆ … ┆ -0.007552 ┆ -0.00156  ┆ -0.216462 ┆ 0.024578 │
│ Alchemist ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Congregat ┆ OTJ       ┆ 0.026857  ┆ 4.308765  ┆ … ┆ -0.014918 ┆ -0.002371 ┆ -0.216462 ┆ 0.036866 │
│ ion Gryff ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Journey   ┆ OTJ       ┆ 0.026228  ┆ 3.047383  ┆ … ┆ -0.004317 ┆ -0.0011   ┆ -0.216462 ┆ 0.018816 │
│ to        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Nowhere   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Oko, the  ┆ OTJ       ┆ 0.026163  ┆ 1.294577  ┆ … ┆ 0.000167  ┆ 0.000469  ┆ -0.216462 ┆ 0.002594 │
│ Ringleade ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ r         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Laughing  ┆ OTJ       ┆ 0.026124  ┆ 1.89099   ┆ … ┆ 0.002603  ┆ 0.002096  ┆ -0.216462 ┆ 0.002575 │
│ Jasper    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Flint     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Aven Inte ┆ OTJ       ┆ 0.024913  ┆ 2.462778  ┆ … ┆ -0.003368 ┆ -0.001416 ┆ -0.216462 ┆ 0.015495 │
│ rrupter   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Frontier  ┆ OTJ       ┆ 0.024717  ┆ 4.50816   ┆ … ┆ -0.010984 ┆ -0.001626 ┆ -0.216462 ┆ 0.030175 │
│ Seeker    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Miriam,   ┆ OTJ       ┆ 0.024598  ┆ 4.313292  ┆ … ┆ -0.016269 ┆ -0.002582 ┆ -0.216462 ┆ 0.037012 │
│ Herd      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Whisperer ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Freestrid ┆ OTJ       ┆ 0.023685  ┆ 1.87985   ┆ … ┆ -0.002162 ┆ -0.001768 ┆ -0.216462 ┆ 0.007786 │
│ er        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lookout   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Trash the ┆ OTJ       ┆ 0.023598  ┆ 4.394304  ┆ … ┆ -0.009066 ┆ -0.001398 ┆ -0.216462 ┆ 0.025548 │
│ Town      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Mana      ┆ OTJ       ┆ 0.023435  ┆ 2.255849  ┆ … ┆ 0.007482  ┆ 0.003884  ┆ -0.216462 ┆ -0.00353 │
│ Drain     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ Generous  ┆ OTJ       ┆ 0.022948  ┆ 2.644901  ┆ … ┆ 0.005613  ┆ 0.001988  ┆ -0.216462 ┆ 0.002425 │
│ Plunderer ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Caustic   ┆ OTJ       ┆ 0.022853  ┆ 1.957838  ┆ … ┆ 0.000198  ┆ 0.000146  ┆ -0.216462 ┆ 0.003463 │
│ Bronco    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Intrepid  ┆ OTJ       ┆ 0.022691  ┆ 3.556304  ┆ … ┆ -0.007935 ┆ -0.001661 ┆ -0.216462 ┆ 0.0203   │
│ Stablemas ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ter       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Rush of   ┆ OTJ       ┆ 0.022567  ┆ 2.539573  ┆ … ┆ 0.000884  ┆ 0.000345  ┆ -0.216462 ┆ 0.007164 │
│ Dread     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Clear     ┆ OTJ       ┆ 0.022492  ┆ 3.40763   ┆ … ┆ -0.006835 ┆ -0.001514 ┆ -0.216462 ┆ 0.018475 │
│ Shot      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Getaway   ┆ OTJ       ┆ 0.022239  ┆ 5.410924  ┆ … ┆ -0.00745  ┆ -0.000803 ┆ -0.216462 ┆ 0.026815 │
│ Glamer    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Honest    ┆ OTJ       ┆ 0.021808  ┆ 3.899089  ┆ … ┆ -0.004975 ┆ -0.000917 ┆ -0.216462 ┆ 0.018995 │
│ Rutstein  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Prairie   ┆ OTJ       ┆ 0.020741  ┆ 3.550979  ┆ … ┆ -0.004791 ┆ -0.001005 ┆ -0.216462 ┆ 0.0156   │
│ Dog       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Prosperit ┆ OTJ       ┆ 0.020706  ┆ 5.127455  ┆ … ┆ -0.009137 ┆ -0.001088 ┆ -0.216462 ┆ 0.025454 │
│ y Tycoon  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Leyline   ┆ OTJ       ┆ 0.020596  ┆ 3.449739  ┆ … ┆ -0.004069 ┆ -0.000887 ┆ -0.216462 ┆ 0.015622 │
│ Binding   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Morbid    ┆ OTJ       ┆ 0.019923  ┆ 2.014493  ┆ … ┆ 0.000136  ┆ 0.000094  ┆ -0.216462 ┆ 0.000094 │
│ Opportuni ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ st        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Assimilat ┆ OTJ       ┆ 0.019721  ┆ 2.554302  ┆ … ┆ 0.005526  ┆ 0.002128  ┆ -0.216462 ┆ 0.000446 │
│ ion Aegis ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Brazen    ┆ OTJ       ┆ 0.019026  ┆ 2.033408  ┆ … ┆ 0.006253  ┆ 0.004186  ┆ -0.216462 ┆ -0.00801 │
│ Borrower  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│ Consuming ┆ OTJ       ┆ 0.018442  ┆ 4.945087  ┆ … ┆ 0.000823  ┆ 0.000104  ┆ -0.216462 ┆ 0.009622 │
│ Ashes     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Shoot the ┆ OTJ       ┆ 0.018316  ┆ 3.858179  ┆ … ┆ 0.001623  ┆ 0.000304  ┆ -0.216462 ┆ 0.005677 │
│ Sheriff   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Primal    ┆ OTJ       ┆ 0.018306  ┆ 3.459141  ┆ … ┆ -0.006379 ┆ -0.001386 ┆ -0.216462 ┆ 0.01631  │
│ Command   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Unfortuna ┆ OTJ       ┆ 0.018188  ┆ 3.89604   ┆ … ┆ 0.001295  ┆ 0.000239  ┆ -0.216462 ┆ 0.006023 │
│ te        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Accident  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Longhorn  ┆ OTJ       ┆ 0.017999  ┆ 3.507873  ┆ … ┆ 0.007638  ┆ 0.001629  ┆ -0.216462 ┆ -0.00289 │
│ Sharpshoo ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ ter       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Desertion ┆ OTJ       ┆ 0.017711  ┆ 3.008909  ┆ … ┆ 0.010903  ┆ 0.002822  ┆ -0.216462 ┆ -0.00692 │

In [28]:
ext = {**ext, **deq_col_specs(pick_equity_mid=0.03)}
col = lambda name: ext[name].expr.alias(name)

df = pl.DataFrame(
    {'deck': deck, 'won_deck': won_deck, 'ata': ata, 'expansion': 'test', 'name': 'test',
        'pct_gp': pct_gp
    }
).with_columns(
    col('won_deck_total'), col('deck_total'), col('deck_small_sample'), pl.col('won_deck').alias('gp_wr') / pl.col('deck')
).with_columns(col('gp_wr_mean')).with_columns(col('gp_wr_bayes_mu')).with_columns(col('gp_wr_b')).with_columns(col('pick_equity'))
    
df

shape: (10, 14)
┌──────┬──────────┬─────┬───────────┬───┬────────────┬────────────────┬──────────┬─────────────┐
│ deck ┆ won_deck ┆ ata ┆ expansion ┆ … ┆ gp_wr_mean ┆ gp_wr_bayes_mu ┆ gp_wr_b  ┆ pick_equity │
│ ---  ┆ ---      ┆ --- ┆ ---       ┆   ┆ ---        ┆ ---            ┆ ---      ┆ ---         │
│ i64  ┆ f64      ┆ i64 ┆ str       ┆   ┆ f64        ┆ f64            ┆ f64      ┆ f64         │
╞══════╪══════════╪═════╪═══════════╪═══╪════════════╪════════════════╪══════════╪═════════════╡
│ 1000 ┆ 500.0    ┆ 11  ┆ test      ┆ … ┆ 0.562069   ┆ 0.548869       ┆ 0.508145 ┆ 0.001598    │
│ 1100 ┆ 570.0    ┆ 10  ┆ test      ┆ … ┆ 0.562069   ┆ 0.552169       ┆ 0.523411 ┆ 0.00284     │
│ 1200 ┆ 640.0    ┆ 9   ┆ test      ┆ … ┆ 0.562069   ┆ 0.555469       ┆ 0.536496 ┆ 0.004438    │
│ 1300 ┆ 710.0    ┆ 8   ┆ test      ┆ … ┆ 0.562069   ┆ 0.558769       ┆ 0.547836 ┆ 0.006391    │
│ 1400 ┆ 780.0    ┆ 7   ┆ test      ┆ … ┆ 0.562069   ┆ 0.562069       ┆ 0.557759 ┆ 0.008698    │
│ 1500 ┆ 850.0    ┆ 6   ┆ test      ┆ … ┆ 0.562069   ┆ 0.565369       ┆ 0.566514 ┆ 0.011361    │
│ 1600 ┆ 920.0    ┆ 5   ┆ test      ┆ … ┆ 0.562069   ┆ 0.568669       ┆ 0.574297 ┆ 0.014379    │
│ 1700 ┆ 990.0    ┆ 4   ┆ test      ┆ … ┆ 0.562069   ┆ 0.571969       ┆ 0.58126  ┆ 0.017751    │
│ 1800 ┆ 1060.0   ┆ 3   ┆ test      ┆ … ┆ 0.562069   ┆ 0.575269       ┆ 0.587527 ┆ 0.021479    │
│ 1900 ┆ 1130.0   ┆ 2   ┆ test      ┆ … ┆ 0.562069   ┆ 0.578569       ┆ 0.593197 ┆ 0.025562    │
└──────┴──────────┴─────┴───────────┴───┴────────────┴────────────────┴──────────┴─────────────┘

In [13]:
df = live_deq(
    "FIN", 
    dt.date(2025,6,24), 
    dt.date(2025,7,15)
)
df.filter(
    ~pl.col("deq").is_null()
).sort(
    "deq", 
    descending =True
).select(
    "name", 
    "deq"
)

shape: (295, 2)
┌────────────────────────────────┬───────────┐
│ name                           ┆ deq       │
│ ---                            ┆ ---       │
│ str                            ┆ f64       │
╞════════════════════════════════╪═══════════╡
│ Smuggler's Copter              ┆ 0.083958  │
│ Nibelheim Aflame               ┆ 0.056846  │
│ Cloud, Midgar Mercenary        ┆ 0.055325  │
│ Ardyn, the Usurper             ┆ 0.050203  │
│ Summon: Primal Odin            ┆ 0.050183  │
│ Dion, Bahamut's Dominant       ┆ 0.050168  │
│ Sazh Katzroy                   ┆ 0.048658  │
│ Jill, Shiva's Dominant         ┆ 0.047918  │
│ Esper Origins                  ┆ 0.047711  │
│ Sephiroth, Fabled SOLDIER      ┆ 0.046119  │
│ Ragavan, Nimble Pilferer       ┆ 0.045915  │
│ Yawgmoth, Thran Physician      ┆ 0.045346  │
│ Dragoon's Lance                ┆ 0.044325  │
│ Winota, Joiner of Forces       ┆ 0.043952  │
│ Memories Returning             ┆ 0.041671  │
│ Cryptic Command                ┆ 0.040669  │
│ Choco-Comet                    ┆ 0.040579  │
│ Loran of the Third Path        ┆ 0.03946   │
│ Traveling Chocobo              ┆ 0.038204  │
│ Atraxa, Grand Unifier          ┆ 0.037593  │
│ Lightning Bolt                 ┆ 0.036806  │
│ Vivi Ornitier                  ┆ 0.036667  │
│ Buster Sword                   ┆ 0.035805  │
│ Summon: Fenrir                 ┆ 0.035613  │
│ Summon: Knights of Round       ┆ 0.035298  │
│ Fatal Push                     ┆ 0.034254  │
│ Kefka, Court Mage              ┆ 0.034159  │
│ The Lunar Whale                ┆ 0.033387  │
│ Ancient Adamantoise            ┆ 0.032807  │
│ Samurai's Katana               ┆ 0.030972  │
│ Machinist's Arsenal            ┆ 0.030927  │
│ Venat, Heart of Hydaelyn       ┆ 0.030106  │
│ Sidequest: Hunt the Mark       ┆ 0.030059  │
│ Summon: Titan                  ┆ 0.030001  │
│ Balamb Garden, SeeD Academy    ┆ 0.029578  │
│ Summon: Leviathan              ┆ 0.029045  │
│ Thunder Magic                  ┆ 0.028856  │
│ Delivery Moogle                ┆ 0.028841  │
│ Yuna, Hope of Spira            ┆ 0.028811  │
│ Ultros, Obnoxious Octopus      ┆ 0.028691  │
│ Eject                          ┆ 0.028508  │
│ White Auracite                 ┆ 0.028488  │
│ Battle Menu                    ┆ 0.028103  │
│ The Emperor of Palamecia       ┆ 0.027816  │
│ The Regalia                    ┆ 0.027445  │
│ Urza, Lord High Artificer      ┆ 0.027344  │
│ Seifer Almasy                  ┆ 0.027066  │
│ Dragoon's Wyvern               ┆ 0.026983  │
│ Sazh's Chocobo                 ┆ 0.026853  │
│ Ice Magic                      ┆ 0.026744  │
│ Zack Fair                      ┆ 0.026184  │
│ Moogles' Valor                 ┆ 0.025608  │
│ Magitek Infantry               ┆ 0.02542   │
│ Zenos yae Galvus               ┆ 0.02523   │
│ Swallowed by Leviathan         ┆ 0.024889  │
│ Akroma's Will                  ┆ 0.024398  │
│ White Mage's Staff             ┆ 0.0243    │
│ Sidequest: Card Collection     ┆ 0.02358   │
│ Sleep Magic                    ┆ 0.023238  │
│ Summon: Bahamut                ┆ 0.023119  │
│ Adelbert Steiner               ┆ 0.02288   │
│ Combat Tutorial                ┆ 0.0228    │
│ Overkill                       ┆ 0.022418  │
│ Cloud of Darkness              ┆ 0.022095  │
│ Shantotto, Tactician Magician  ┆ 0.02189   │
│ Dark Confidant                 ┆ 0.021473  │
│ Kuja, Genome Sorcerer          ┆ 0.021441  │
│ Absolute Virtue                ┆ 0.020613  │
│ Sephiroth's Intervention       ┆ 0.020343  │
│ Il Mheg Pixie                  ┆ 0.020302  │
│ Deadly Dispute                 ┆ 0.019837  │
│ Cornered by Black Mages        ┆ 0.019373  │
│ Sahagin                        ┆ 0.019341  │
│ Dreams of Laguna               ┆ 0.019044  │
│ Ambrosia Whiteheart            ┆ 0.018903  │
│ Counterspell                   ┆ 0.018299  │
│ Lightning, Army of One         ┆ 0.01825   │
│ Midgar, City of Mako           ┆ 0.018144  │
│ Jenova, Ancient Calamity       ┆ 0.017875  │
│ Firion, Wild Rose Warrior      ┆ 0.017849  │
│ Ignis Scientia                 ┆ 0.017344  │
│ Chocobo Kick                   ┆ 0.016846  │
│ Aerith Gainsborough            ┆ 0.016557  │
│ Summon: Primal Garuda          ┆ 0.016416  │
│ Suplex                         ┆ 0.016413  │
│ Town Greeter                   ┆ 0.016289  │
│ Fire Magic                     ┆ 0.016158  │
│ Zanarkand, Ancient Metropolis  ┆ 0.015712  │
│ Torgal, A Fine Hound           ┆ 0.015476  │
│ Coliseum Behemoth              ┆ 0.015339  │
│ Slash of Light                 ┆ 0.014983  │
│ Summon: Fat Chocobo            ┆ 0.014938  │
│ Captain Lannery Storm          ┆ 0.014854  │
│ Sorceress's Schemes            ┆ 0.014726  │
│ Call the Mountain Chocobo      ┆ 0.014538  │
│ Summon: G.F. Cerberus          ┆ 0.014365  │
│ Circle of Power                ┆ 0.014253  │
│ Venser, Shaper Savant          ┆ 0.01406   │
│ Ninja's Blades                 ┆ 0.013597  │
│ Astrologian's Planisphere      ┆ 0.013571  │
│ Gaelicat                       ┆ 0.013509  │
│ Restoration Magic              ┆ 0.012575  │
│ Magitek Armor                  ┆ 0.012439  │
│ Vanille, Cheerful l'Cie        ┆ 0.012428  │
│ Rufus Shinra                   ┆ 0.011719  │
│ Wall of Omens                  ┆ 0.01164   │
│ Vayne's Treachery              ┆ 0.011514  │
│ The Crystal's Chosen           ┆ 0.010999  │
│ Starting Town                  ┆ 0.010967  │
│ Raubahn, Bull of Ala Mhigo     ┆ 0.010446  │
│ Zell Dincht                    ┆ 0.010022  │
│ Jecht, Reluctant Guardian      ┆ 0.009911  │
│ Summon: Shiva                  ┆ 0.009598  │
│ Quistis Trepe                  ┆ 0.00935   │
│ Prompto Argentum               ┆ 0.00854   │
│ Vincent Valentine              ┆ 0.008432  │
│ Exdeath, Void Warlock          ┆ 0.008386  │
│ Blazing Bomb                   ┆ 0.00824   │
│ Paladin's Arms                 ┆ 0.00807   │
│ Syr Konrad, the Grim           ┆ 0.007602  │
│ The Final Days                 ┆ 0.007421  │
│ Syncopate                      ┆ 0.00725   │
│ Judge Magister Gabranth        ┆ 0.007202  │
│ Joshua, Phoenix's Dominant     ┆ 0.007187  │
│ Dark Knight's Greatsword       ┆ 0.006981  │
│ Relm's Sketching               ┆ 0.006831  │
│ Y'shtola Rhul                  ┆ 0.006781  │
│ Garnet, Princess of Alexandria ┆ 0.006741  │
│ Squall, SeeD Mercenary         ┆ 0.006511  │
│ Ride the Shoopuf               ┆ 0.00638   │
│ Ultima                         ┆ 0.006284  │
│ Goobbue Gardener               ┆ 0.006225  │
│ Cid, Timeless Artificer        ┆ 0.00605   │
│ Emet-Selch, Unsundered         ┆ 0.005992  │
│ Al Bhed Salvagers              ┆ 0.00578   │
│ Capital City                   ┆ 0.005646  │
│ Scorpion Sentinel              ┆ 0.005506  │
│ Weapons Vendor                 ┆ 0.005487  │
│ Garland, Knight of Cornelia    ┆ 0.005422  │
│ Zidane, Tantalus Thief         ┆ 0.005399  │
│ Giott, King of the Dwarves     ┆ 0.00539   │
│ Resentful Revelation           ┆ 0.004932  │
│ Diamond Weapon                 ┆ 0.004903  │
│ Ashe, Princess of Dalmasca     ┆ 0.004894  │
│ Fynn, the Fangbearer           ┆ 0.004838  │
│ Stuck in Summoner's Sanctum    ┆ 0.004652  │
│ Retrieve the Esper             ┆ 0.004432  │
│ You're Not Alone               ┆ 0.003951  │
│ Gogo, Master of Mimicry        ┆ 0.003877  │
│ Omega, Heartless Evolution     ┆ 0.003652  │
│ Black Mage's Rod               ┆ 0.003054  │
│ Light Up the Stage             ┆ 0.002952  │
│ Gladiolus Amicitia             ┆ 0.002725  │
│ Gran Pulse Ochu                ┆ 0.002721  │
│ Balamb T-Rexaur                ┆ 0.002702  │
│ Locke Cole                     ┆ 0.002555  │
│ Baron, Airship Kingdom         ┆ 0.002534  │
│ Crossroads Village             ┆ 0.002291  │
│ Demon Wall                     ┆ 0.002256  │
│ Phantom Train                  ┆ 0.001906  │
│ Evil Reawakened                ┆ 0.001903  │
│ Danitha Capashen, Paragon      ┆ 0.001765  │
│ Lindblum, Industrial Regency   ┆ 0.00153   │
│ Shinra Reinforcements          ┆ 0.001485  │
│ Tifa Lockhart                  ┆ 0.001047  │
│ Undercity Dire Rat             ┆ 0.000851  │
│ Bartz and Boko                 ┆ 0.000494  │
│ The Wind Crystal               ┆ 0.000375  │
│ Sidequest: Raise a Chocobo     ┆ 0.00027   │
│ Gohn, Town of Ruin             ┆ 0.000143  │
│ Farseek                        ┆ 0.000121  │
│ Fate of the Sun-Cryst          ┆ -0.00001  │
│ Clash of the Eikons            ┆ -0.000054 │
│ Travel the Overworld           ┆ -0.000157 │
│ Coral Sword                    ┆ -0.000258 │
│ Rinoa Heartilly                ┆ -0.000311 │
│ Ultimecia, Time Sorceress      ┆ -0.000319 │
│ Cecil, Dark Knight             ┆ -0.000336 │
│ Self-Destruct                  ┆ -0.000555 │
│ Reach the Horizon              ┆ -0.000586 │
│ Bard's Bow                     ┆ -0.000639 │
│ Adventurer's Inn               ┆ -0.000704 │
│ Airship Crash                  ┆ -0.000719 │
│ Eden, Seat of the Sanctum      ┆ -0.000762 │
│ PuPu UFO                       ┆ -0.000955 │
│ Kain, Traitorous Dragoon       ┆ -0.00101  │
│ Gongaga, Reactor Town          ┆ -0.001133 │
│ Ring of the Lucii              ┆ -0.001173 │
│ Cloudbound Moogle              ┆ -0.001308 │
│ Haste Magic                    ┆ -0.001387 │
│ Gilgamesh, Master-at-Arms      ┆ -0.001532 │
│ Sin, Spira's Punishment        ┆ -0.001714 │
│ Qutrub Forayer                 ┆ -0.001789 │
│ Loporrit Scout                 ┆ -0.001826 │
│ Tonberry                       ┆ -0.001834 │
│ Blitzball Shot                 ┆ -0.001835 │
│ G'raha Tia                     ┆ -0.001927 │
│ Balthier and Fran              ┆ -0.001931 │
│ Warrior's Sword                ┆ -0.001942 │
│ Coeurl                         ┆ -0.002034 │
│ Laughing Mad                   ┆ -0.002204 │
│ The Gold Saucer                ┆ -0.002224 │
│ Terra, Magical Adept           ┆ -0.002246 │
│ Hecteyes                       ┆ -0.00226  │
│ Cargo Ship                     ┆ -0.002267 │
│ Brainstorm                     ┆ -0.002287 │
│ Tellah, Great Sage             ┆ -0.00229  │
│ Commune with Beavers           ┆ -0.002292 │
│ Adventurer's Airship           ┆ -0.002353 │
│ Treno, Dark City               ┆ -0.002391 │
│ Unexpected Request             ┆ -0.002435 │
│ Summon: Choco/Mog              ┆ -0.002447 │
│ Ishgard, the Holy See          ┆ -0.002525 │
│ Ether                          ┆ -0.002549 │
│ Queen Brahne                   ┆ -0.002593 │
│ Rydia, Summoner of Mist        ┆ -0.002672 │
│ Mysidian Elder                 ┆ -0.0027   │
│ Magic Pot                      ┆ -0.002807 │
│ Magic Damper                   ┆ -0.002902 │
│ Sidequest: Catch a Fish        ┆ -0.002914 │
│ Auron's Inspiration            ┆ -0.002998 │
│ Dwarven Castle Guard           ┆ -0.00308  │
│ Phoenix Down                   ┆ -0.003105 │
│ Aerith Rescue Mission          ┆ -0.003189 │
│ Snow Villiers                  ┆ -0.003277 │
│ Instant Ramen                  ┆ -0.003331 │
│ Lunatic Pandora                ┆ -0.003406 │
│ Chocobo Racetrack              ┆ -0.003414 │
│ Windurst, Federation Center    ┆ -0.003511 │
│ Stiltzkin, Moogle Merchant     ┆ -0.003545 │
│ Gaius van Baelsar              ┆ -0.003582 │
│ Guadosalam, Farplane Gateway   ┆ -0.003622 │
│ Malboro                        ┆ -0.003634 │
│ Gysahl Greens                  ┆ -0.00398  │
│ Freya Crescent                 ┆ -0.004035 │
│ Sidequest: Play Blitzball      ┆ -0.004079 │
│ Lion Heart                     ┆ -0.004196 │
│ Edgar, King of Figaro          ┆ -0.004237 │
│ Summon: Brynhildr              ┆ -0.004299 │
│ Monk's Fist                    ┆ -0.004373 │
│ Red Mage's Rapier              ┆ -0.004396 │
│ Crystal Fragments              ┆ -0.004454 │
│ Insomnia, Crown City           ┆ -0.004693 │
│ Tidus, Blitzball Star          ┆ -0.004731 │
│ Opera Love Song                ┆ -0.004883 │
│ Jumbo Cactuar                  ┆ -0.005039 │
│ Vector, Imperial Capital       ┆ -0.005051 │
│ Zodiark, Umbral God            ┆ -0.005089 │
│ Tifa's Limit Break             ┆ -0.005157 │
│ Light of Judgment              ┆ -0.005198 │
│ Barret Wallace                 ┆ -0.005261 │
│ Sabotender                     ┆ -0.005388 │
│ The Earth Crystal              ┆ -0.005408 │
│ World Map                      ┆ -0.005496 │
│ Vincent's Limit Break          ┆ -0.005527 │
│ Matoya, Archon Elder           ┆ -0.005567 │
│ Ahriman                        ┆ -0.005603 │
│ Item Shopkeep                  ┆ -0.005661 │
│ Sharlayan, Nation of Scholars  ┆ -0.005663 │
│ Fight On!                      ┆ -0.005665 │
│ Ice Flan                       ┆ -0.005666 │
│ Choco, Seeker of Paradise      ┆ -0.005888 │
│ Summon: Esper Ramuh            ┆ -0.006076 │
│ Namazu Trader                  ┆ -0.00609  │
│ Prishe's Wanderings            ┆ -0.006258 │
│ Triple Triad                   ┆ -0.00643  │
│ The Prima Vista                ┆ -0.006482 │
│ Hope Estheim                   ┆ -0.006588 │
│ Summon: G.F. Ifrit             ┆ -0.006629 │
│ Rydia's Return                 ┆ -0.006648 │
│ Sage's Nouliths                ┆ -0.006763 │
│ Sandworm                       ┆ -0.006809 │
│ Minwu, White Mage              ┆ -0.006967 │
│ The Darkness Crystal           ┆ -0.007014 │
│ Clive, Ifrit's Dominant        ┆ -0.007196 │
│ Ultima, Origin of Oblivion     ┆ -0.007311 │
│ Rabanastre, Royal City         ┆ -0.007511 │
│ Relentless X-ATM092            ┆ -0.007539 │
│ Reno and Rude                  ┆ -0.007619 │
│ Qiqirn Merchant                ┆ -0.007801 │
│ Rook Turret                    ┆ -0.007838 │
│ Poison the Waters              ┆ -0.008298 │
│ Gigantoad                      ┆ -0.008485 │
│ Thief's Knife                  ┆ -0.008737 │
│ Jidoor, Aristocratic Capital   ┆ -0.008916 │
│ The Wandering Minstrel         ┆ -0.01003  │
│ Black Waltz No. 3              ┆ -0.010125 │
│ Hill Gigas                     ┆ -0.010291 │
│ Valkyrie Aerial Unit           ┆ -0.011241 │
│ Quina, Qu Gourmet              ┆ -0.012011 │
│ Blitzball                      ┆ -0.013405 │
│ Shambling Cie'th               ┆ -0.014891 │
│ Golbez, Crystal Collector      ┆ -0.015304 │
│ Summon: Anima                  ┆ -0.015872 │
│ Fang, Fearless l'Cie           ┆ -0.017759 │
└────────────────────────────────┴───────────┘

In [2]:
!spells refresh EOE

  🪄 spells ✨ [data home]=/home/joel/.local/share/spells/

  🪄 refresh ✨ Downloading draft dataset from 17Lands.com
100% [..................................................] 141599552 / 141599552
  🪄 refresh ✨ Unzipping and transforming to parquet (this might take a few minutes)...
  🪄 refresh ✨ Wrote file /home/joel/.local/share/spells/external/EOE/EOE_PremierDraft_draft.parquet
  🪄 clean ✨ No local cache found for set EOE
  🪄 refresh ✨ Fetching card data from mtgjson.com and writing card file
  🪄 refresh ✨ Wrote file /home/joel/.local/share/spells/external/EOE/EOE_card.parquet
  🪄 refresh ✨ Calculating set context
  🪄 refresh ✨ Wrote file /home/joel/.local/share/spells/external/EOE/EOE_PremierDraft_context.parquet
  🪄 refresh ✨ Downloading game dataset from 17Lands.com
100% [....................................................] 45587793 / 45587793
  🪄 refresh ✨ Unzipping and transforming to parquet (this might take a few minutes)...
  🪄 error ✨ Bad schema found, loading dataset into memory and attempting to cast to correct schema
  🪄 refresh ✨ Wrote file /home/joel/.local/share/spells/external/EOE/EOE_PremierDraft_game.parquet
  🪄 clean ✨ Removed 1 files from local cache for set EOE
  🪄 clean ✨ Removed local cache dir /home/joel/.local/share/spells/cache/EOE

In [17]:
from spells import summon
import polars as pl
pl.Config.set_tbl_rows(500)

ugwr="user_game_win_rate_bucket"
df=summon("EOE", 
       ["num_drafts"],
       group_by=[ugwr],
       filter_spec={
           "$or": [
               {"op": "=", 
                "lhs": "event_match_wins",
                "rhs": 7
               },
               {
               "op": "=", 
                "lhs": "event_match_losses",
                "rhs": 3
               }
           ]
       }
      ).filter(
    (pl.col(ugwr)>0.34)&(pl.col(ugwr)<0.73)
)
print(df)

shape: (19, 2)
┌───────────────────────────┬────────────┐
│ user_game_win_rate_bucket ┆ num_drafts │
│ ---                       ┆ ---        │
│ f64                       ┆ i32        │
╞═══════════════════════════╪════════════╡
│ 0.36                      ┆ 704        │
│ 0.38                      ┆ 680        │
│ 0.4                       ┆ 1948       │
│ 0.42                      ┆ 2347       │
│ 0.44                      ┆ 3147       │
│ 0.46                      ┆ 5010       │
│ 0.48                      ┆ 5762       │
│ 0.5                       ┆ 8738       │
│ 0.52                      ┆ 8795       │
│ 0.54                      ┆ 9134       │
│ 0.56                      ┆ 8615       │
│ 0.58                      ┆ 6960       │
│ 0.6                       ┆ 6077       │
│ 0.62                      ┆ 3886       │
│ 0.64                      ┆ 2513       │
│ 0.66                      ┆ 1364       │
│ 0.68                      ┆ 837        │
│ 0.7                       ┆ 419        │
│ 0.72                      ┆ 194        │
└───────────────────────────┴────────────┘